### ISSUE TITLE
feature request multiple streams

### ISSUE THREAD

**Issue by netxer** [NiciusB/twitch-drops-lurker#1]
As the titles states would it be possible to add config/verible for watching multiple streams?

Another request is would it possible to make the lurker bot collect channle points and redeem random emotes?

**Comment by NiciusB** [comment]
Edit: I misunderstood the question.

Watching multiple streams will not actually increase your chances of drops, so there's no point for it. 

I thought about channel points, but I'm not sure about the ethical problems. Sure, this whole thing is pretty sketchy but adding that feature would, in my opinion, cross the line. Would love to hear other people's thoughts on this, tho.
