### ISSUE TITLE
does work on repl?

### ISSUE THREAD

**Issue by AzuKaOwO** [NiciusB/twitch-drops-lurker#14]
hello i just tried in repl but seem not work 
its possbile make work in repl?

**Comment by NiciusB** [comment]
Hi! I’m not familiar with Repl but I don’t see why it wouldn’t work. What is the exact error? Also make sure to install Chrome and follow the installation instructions

**Comment by AzuKaOwO** [comment]
> Hi! I’m not familiar with Repl but I don’t see why it wouldn’t work. What is the exact error? Also make sure to install Chrome and follow the installation instructions

HI! i tried on repl seem not work bcz
in .env there is path=
repl its just a host thing i just really want run 24/7
nvm thanks
