### ISSUE TITLE
Games names

### ISSUE THREAD

**Issue by Tennsh** [NiciusB/twitch-drops-lurker#7]
It doesnt work with the games whose names contain spaces and another special symbols. Sometimes it tooks a long time before it found someone, sometimes doesnt work at all...
Monitoring webserver listening at http://localhost:5000
� Looking for a streamer to watch
� No live streams found!
� Looking for a streamer to watch
� No live streams found!
� Looking for a streamer to watch
� No live streams found!
For example
GAME=Gwent%3A%20The%20Witcher%20Card%20Game doesnt found anyone, im tried with the another games, it works with apex legend after a long wait.

**Comment by Tennsh** [comment]
Considering to the screenshot, it try to find streams by "drops enabled" filter, but some games like "gwent", doesnt have this filter option, and another games like "Don't Starve Together" have it, but streamers just dont use it, but they have this feature enabled actualy. Maybe be a thing to add option, if there is no streams with "drops enebled" filter, it just connect any streamer in this game category.

**Comment by mt025** [comment]
It's the same with Rainbow Six Siege; However they do have a drops notification shown on the page, just not the drops enabled tag.

![Siege Image](https://user-images.githubusercontent.com/2631330/105384660-69d61c00-5c0a-11eb-9a1c-1b0bc99b296d.png)
